import memes from "../assets/image/memes";

const httpcodigoMemes = [
  { id: 1, codigo: 100, description: "El servidor dice: seguí, todavía no pasó nada.", image: memes["./100.webp"] },
  { id: 2, codigo: 101, description: "Cambiando de protocolo, ahora todo es distinto.", image: memes["./101.webp"] },
  { id: 3, codigo: 102, description: "Procesando… el backend está pensando.", image: memes["./102.webp"] },

  { id: 4, codigo: 200, description: "Todo salió perfecto ", image: memes["./200.webp"] },
  { id: 5, codigo: 201, description: "Se creó algo nuevo y funciona.", image: memes["./201.webp"] },
  { id: 6, codigo: 202, description: "Aceptado… pero todavía no terminó.", image: memes["./202.webp"] },
  { id: 7, codigo: 204, description: "No hay contenido, pero todo bien.", image: memes["./204.webp"] },
  { id: 8, codigo: 206, description: "Te mandé solo una parte.", image: memes["./206.webp"] },

  { id: 9, codigo: 300, description: "Elegí un camino… cualquiera.", image: memes["./300.webp"] },
  { id: 10, codigo: 301, description: "Me mudé, no vuelvo más.", image: memes["./301.webp"] },
  { id: 11, codigo: 302, description: "Está, pero no acá, es temporal.", image: memes["./302.webp"] },
  { id: 12, codigo: 303, description: "Mirá en otro lado.", image: memes["./303.webp"] },
  { id: 13, codigo: 304, description: "No cambió nada desde la última vez.", image: memes["./304.webp"] },
  { id: 15, codigo: 307, description: "Redirección temporal, tranqui.", image: memes["./307.webp"] },
  { id: 16, codigo: 308, description: "Redirección permanente, en serio.", image: memes["./308.webp"] },

  { id: 17, codigo: 400, description: "El pedido está mal, algo hiciste.", image: memes["./400.webp"] },
  { id: 18, codigo: 401, description: "¿Quién sos? Logueate primero.", image: memes["./401.webp"] },
  { id: 19, codigo: 402, description: "Pagá y hablamos.", image: memes["./402.webp"] },
  { id: 20, codigo: 403, description: "No tenés permiso ", image: memes["./403.webp"] },
  { id: 21, codigo: 404, description: "Esto no existe.", image: memes["./404.webp"] },
  { id: 22, codigo: 405, description: "Ese método no va.", image: memes["./405.webp"] },
  { id: 23, codigo: 406, description: "No es aceptable.", image: memes["./406.webp"] },
  { id: 24, codigo: 408, description: "Tardaste demasiado.", image: memes["./408.webp"] },
  { id: 25, codigo: 409, description: "Conflicto detectado.", image: memes["./409.webp"] },
  { id: 26, codigo: 410, description: "Se fue y no vuelve.", image: memes["./410.webp"] },
  { id: 27, codigo: 411, description: "Falta el largo del contenido.", image: memes["./411.webp"] },
  { id: 28, codigo: 412, description: "La condición falló.", image: memes["./412.webp"] },
  { id: 29, codigo: 413, description: "Demasiado pesado.", image: memes["./413.webp"] },
  { id: 30, codigo: 414, description: "URL larguísima.", image: memes["./414.webp"] },
  { id: 31, codigo: 415, description: "Formato no soportado.", image: memes["./415.webp"] },
  { id: 32, codigo: 416, description: "Ese rango no existe.", image: memes["./416.webp"] },
  { id: 33, codigo: 417, description: "La expectativa falló.", image: memes["./417.webp"] },
  { id: 34, codigo: 418, description: "Soy una tetera ", image: memes["./418.webp"] },
  { id: 35, codigo: 421, description: "Pedido mal dirigido.", image: memes["./421.webp"] },
  { id: 36, codigo: 422, description: "No se puede procesar.", image: memes["./422.webp"] },
  { id: 37, codigo: 423, description: "Está bloqueado 🔒", image: memes["./423.webp"] },
  { id: 38, codigo: 424, description: "Dependencia fallida.", image: memes["./424.webp"] },
  { id: 39, codigo: 425, description: "Demasiado pronto.", image: memes["./425.webp"] },
  { id: 40, codigo: 426, description: "Actualizá primero.", image: memes["./426.webp"] },
  { id: 41, codigo: 429, description: "Pará un poco ", image: memes["./429.webp"] },
  { id: 42, codigo: 431, description: "Headers enormes.", image: memes["./431.webp"] },
  { id: 43, codigo: 451, description: "Bloqueado por ley ", image: memes["./451.webp"] },

  { id: 44, codigo: 500, description: "Explotó el servidor ", image: memes["./500.webp"] },
  { id: 45, codigo: 501, description: "Todavía no está hecho.", image: memes["./501.webp"] },
  { id: 46, codigo: 502, description: "El gateway falló.", image: memes["./502.webp"] },
  { id: 47, codigo: 503, description: "No disponible ahora.", image: memes["./503.webp"] },
  { id: 48, codigo: 504, description: "Timeout total.", image: memes["./504.webp"] },
  { id: 49, codigo: 506, description: "Negociación rara.", image: memes["./506.webp"] },
  { id: 50, codigo: 507, description: "Sin espacio.", image: memes["./507.webp"] },
  { id: 51, codigo: 508, description: "Loop infinito ", image: memes["./508.webp"] },
  { id: 52, codigo: 510, description: "Falta extender.", image: memes["./510.webp"] },
  { id: 53, codigo: 511, description: "Autenticación de red requerida.", image: memes["./511.webp"] },
];

export default httpcodigoMemes;
